# permissions for end users to view nodedrains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedrain-viewer-role
rules:
- apiGroups:
  - gezb.io
  resources:
  - nodedrains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gezb.io
  resources:
  - nodedrains/status
  verbs:
  - get
