# permissions for end users to edit nodedrains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedrain-editor-role
rules:
- apiGroups:
  - gezb.io
  resources:
  - nodedrains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gezb.io
  resources:
  - nodedrains/status
  verbs:
  - get
